### ISSUE TITLE
Readable Error for unconfigured values

### ISSUE THREAD

**Issue by kaikuchn** [cloud66-oss/konfig#4]
Hey,

thanks for releasing this gem, I'm currently giving it a try and so far it looks good. One thing that would be nice is if you could handle missing settings. Right now one get's a stack trace about a missing method on hash which is a little hard to read.

E.g.,

```
NoMethodError: undefined method `password' for #<Hash:0x00007fa844c016a8>
/Users/***/code/foo/vendor/bundle/gems/hash_dot-2.4.2/lib/hash.rb:30:in `method_missing'
/Users/***/code/foo/config/initializers/bar.rb:5:in `<top (required)>'
[....]
```

I've truncated the Stacktrace to the interesting parts. I think the error would be easier to read if you catch it and throw your own more meaningful error message.

Best regards,
Kai

**Comment by khash** [comment]
Thank you for the suggestion @kaikuchn we might implement this is possible as `Settings` relies on dynamic method names which might not be easy to override. However you can always use the `schema` support in Konfig which would read and validate the cofiguration for presence and type before the app starts and shows much better errors.
